name: ci
on: [ push, workflow_dispatch ]

jobs:
  build:
    name: Build
    if: ${{ !contains(github.event.head_commit.message, 'skip build') }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        variant: [ hydro-stations, hydro-observations, hydro-predictions, piezo-stations, piezo-observations ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}
      - name: Setup workspace
        env:
          KALISIO_GITHUB_URL: ${{ secrets.KALISIO_GITHUB_URL }}
        run: bash ./scripts/setup_workspace.sh
      - name: Build job
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: bash ./scripts/build.sh -p -r ${{ github.job }} -v ${{ matrix.variant }}
