name: ci
on: [ push ]

jobs:
  build:
    name: Build
    if: ${{ !contains(github.event.head_commit.message, 'skip build') }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        variant: [hydro-stations, hydro-observations, hydro-predictions, piezo-stations, piezo-observations]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}
      - name: Setup workspace
        env:
          GITHUB_DEVELOPMENT_PAT: ${{ secrets.GH_DEVELOPMENT_PAT }}
        run: bash ./scripts/setup_workspace.sh
      - name: Build job
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: bash ./scripts/build.sh -p -r ${{ github.job }} ${{ matrix.variant }}
 